# Base Configuration for SMU LpGBT v1
base:
  v0:
  v1:

    "LPGBT.RWF.CALIBRATION.VREFENABLE": 1               
    "LPGBT.RWF.CALIBRATION.VREFTUNE": 0x63              

    # CLOCKGENERATOR 
    # 20:E8
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCALIBRATIONENDOFCOUNT": 0xE 
    "LPGBT.RWF.CLOCKGENERATOR.CLKGBIASGENCONFIG": 0x8  
    # From 21:38
    "LPGBT.RWF.CLOCKGENERATOR.CDRCONTROLOVERRIDEENABLE": 0     
    "LPGBT.RWF.CLOCKGENERATOR.CLKGDISABLEFRAMEALIGNERLOCKCONTROL": 0  
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRRES": 1                   
    "LPGBT.RWF.CLOCKGENERATOR.CLKGVCORAILMODE": 1              
    "LPGBT.RWF.CLOCKGENERATOR.CLKGVCODAC": 0x8                 
    # From 22:22
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLRESWHENLOCKED": 0x2       
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLRES": 0x2                 
    # From 23:99
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLINTCURWHENLOCKED": 0x9  
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLINTCUR": 0x9             
    # From 24:99
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLPROPCURWHENLOCKED": 0x9 
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLPROPCUR": 0x9            
    # From 25:55
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRPROPCURWHENLOCKED": 0x5  
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRPROPCUR": 0x5            
    # From 26:55
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRINTCURWHENLOCKED": 0x5   
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRINTCUR": 0x5            
    # From 27:66
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRFEEDFORWARDPROPCURWHENLOCKED": 0x6 
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRFEEDFORWARDPROPCUR": 0x6 
    # From 28:55
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFLLINTCURWHENLOCKED": 0x5   
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFLLINTCUR": 0x5 
              
    # From 29:1B
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOCONNECTCDR": 0             
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCAPBANKOVERRIDEENABLE": 0   
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFEEDFORWARDCAPWHENLOCKED": 0x3 
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFEEDFORWARDCAP": 0x3        
    
    # CLKGCntOverride (0x2A) 
    # "LPGBT.RWF.CLOCKGENERATOR.CLKGCOOVERRIDEVC": 0
    # "LPGBT.RWF.CLOCKGENERATOR.CDRCOREFCLKSEL": 0
    # "LPGBT.RWF.CLOCKGENERATOR.CDRCOENABLEPLL": 0
    # "LPGBT.RWF.CLOCKGENERATOR.CDRCOENABLEFD": 0
    # "LPGBT.RWF.CLOCKGENERATOR.CDRCOENABLECDR": 0
    # "LPGBT.RWF.CLOCKGENERATOR.CDRCODISDATACOUNTERREF": 0
    # "LPGBT.RWF.CLOCKGENERATOR.CDRCODISDESVBIASGEN": 0
    # "LPGBT.RWF.CLOCKGENERATOR.CDRCOCONNECTPLL": 0
    # "LPGBT.RWF.CLOCKGENERATOR.CLKGCAPBANKSELECT_7TO0": 0x00   
    
    # From 002C:88
    "LPGBT.RWF.CLOCKGENERATOR.CLKGWAITCDRTIME": 0x8           
    "LPGBT.RWF.CLOCKGENERATOR.CLKGWAITPLLTIME": 0x8           

    # From 002D:8F
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERENABLE": 1        
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERCLKALWAYSON": 0  
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCAPBANKSELECT_8": 0         
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERLOCKTHRCOUNTER": 0xF 

    # From 002E:FF
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERRELOCKTHRCOUNTER": 0xF
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERUNLOCKTHRCOUNTER": 0xF 

    # From 002F:10
    "LPGBT.RWF.CLOCKGENERATOR.FAMAXHEADERFOUNDCOUNT": 0x10      

    # From 30:10
    "LPGBT.RWF.CLOCKGENERATOR.FAMAXHEADERFOUNDCOUNTAFTERNF": 0x10 
    "LPGBT.RWF.CLOCKGENERATOR.FAMAXHEADERNOTFOUNDCOUNT": 0x10   

    # From 33:59
    "LPGBT.RWF.CLOCKGENERATOR.PSDLLCONFIRMCOUNT": 0x2        
    "LPGBT.RWF.CLOCKGENERATOR.PSDLLCURRENTSEL": 0x1           

    # # FORCEEnable (0x35) 
    # "LPGBT.RWF.CLOCKGENERATOR.FORCETXENABLE": 0
    # "LPGBT.RWF.CLOCKGENERATOR.FORCERXENABLE": 0
    # "LPGBT.RWF.CLOCKGENERATOR.LDFORCEENABLE": 0
    # "LPGBT.RWF.CLOCKGENERATOR.I2CMCLKALWAYSENABLE": 0 
    # "LPGBT.RWF.CLOCKGENERATOR.PSFSMCLKALWAYSON": 0    

    # CHIPCONFIG (Address 0x036 : 40)
    "LPGBT.RWF.CHIPCONFIG.HIGHSPEEDDATAOUTINVERT": 1
    "LPGBT.RWF.CHIPCONFIG.HIGHSPEEDDATAININVERT": 0   
    "LPGBT.RWF.CHIPCONFIG.CHIPADDRESSBAR": 0          

    # EQUALIZER (Addresses 0x037:18)
    "LPGBT.RWF.EQUALIZER.EQATTENUATION": 0x3   
    "LPGBT.RWF.EQUALIZER.EQCAP": 0x0                  

    # LINE_DRIVER # From 39:EF
    "LPGBT.RWF.LINE_DRIVER.LDEMPHASISENABLE": 1       
    "LPGBT.RWF.LINE_DRIVER.LDMODULATIONCURRENT": 0x6F 

    # From 003A:30
    "LPGBT.RWF.LINE_DRIVER.LDEMPHASISSHORT": 0        
    "LPGBT.RWF.LINE_DRIVER.LDEMPHASISAMP": 0x30      

    # # REFCLK (0x3B) 
    # "LPGBT.RWF.LINE_DRIVER.REFCLKFORCEENABLE": 0      
    # "LPGBT.RWF.LINE_DRIVER.REFCLKACBIAS": 1           
    # "LPGBT.RWF.LINE_DRIVER.REFCLKTERM": 1             
    # # SCCONFIG (0x3C) 
    # "LPGBT.RWF.LINE_DRIVER.SCPARITYCHECKDISABLE": 0   

    # # RESET (Address 0x03D) 
    # "LPGBT.RWF.RESET.BODENABLE": 0                    
    # "LPGBT.RWF.RESET.BODLEVEL": 0                     

    # # POWER_GOOD (Address 0x03E)
    # "LPGBT.RWF.POWER_GOOD.PGENABLE": 1
    # "LPGBT.RWF.POWER_GOOD.PGLEVEL": 4
    # "LPGBT.RWF.POWER_GOOD.PGDELAY": 0xC

    # EPORTCLK (0x6E - 0xA7)
    # EPCLK0 006E:19
    "LPGBT.RWF.EPORTCLK.EPCLK0LOWRES": 0               
    "LPGBT.RWF.EPORTCLK.EPCLK0INVERT": 0               
    "LPGBT.RWF.EPORTCLK.EPCLK0DRIVESTRENGTH": 3        
    "LPGBT.RWF.EPORTCLK.EPCLK0FREQ": 1                 
    
    # 006F
    # "LPGBT.RWF.EPORTCLK.EPCLK0PREEMPHASISSTRENGTH": 0
    # "LPGBT.RWF.EPORTCLK.EPCLK0PREEMPHASISMODE": 0
    # "LPGBT.RWF.EPORTCLK.EPCLK0PREEMPHASISWIDTH": 0
    
    # From 74:19 EPCLK3ChnCntrH
    "LPGBT.RWF.EPORTCLK.EPCLK3LOWRES": 0              
    "LPGBT.RWF.EPORTCLK.EPCLK3INVERT": 0              
    "LPGBT.RWF.EPORTCLK.EPCLK3DRIVESTRENGTH": 3       
    "LPGBT.RWF.EPORTCLK.EPCLK3FREQ": 1  

    #0x075 EPCLK3ChnCntrL               
    "LPGBT.RWF.EPORTCLK.EPCLK3PREEMPHASISSTRENGTH": 0 
    "LPGBT.RWF.EPORTCLK.EPCLK3PREEMPHASISMODE": 0     
    "LPGBT.RWF.EPORTCLK.EPCLK3PREEMPHASISWIDTH": 0    

    # From 007E:19
    "LPGBT.RWF.EPORTCLK.EPCLK8LOWRES": 0               
    "LPGBT.RWF.EPORTCLK.EPCLK8INVERT": 0              
    "LPGBT.RWF.EPORTCLK.EPCLK8DRIVESTRENGTH": 3      
    "LPGBT.RWF.EPORTCLK.EPCLK8FREQ": 1                
    "LPGBT.RWF.EPORTCLK.EPCLK8PREEMPHASISSTRENGTH": 0  
    "LPGBT.RWF.EPORTCLK.EPCLK8PREEMPHASISMODE": 0      
    "LPGBT.RWF.EPORTCLK.EPCLK8PREEMPHASISWIDTH": 0     

    # For 0x9C:19 EPCLK23.------------------------
    "LPGBT.RWF.EPORTCLK.EPCLK23LOWRES": 0             
    "LPGBT.RWF.EPORTCLK.EPCLK23INVERT": 0             
    "LPGBT.RWF.EPORTCLK.EPCLK23DRIVESTRENGTH": 3      
    "LPGBT.RWF.EPORTCLK.EPCLK23FREQ": 1               
    "LPGBT.RWF.EPORTCLK.EPCLK23PREEMPHASISSTRENGTH": 0  
    "LPGBT.RWF.EPORTCLK.EPCLK23PREEMPHASISMODE": 0     
    "LPGBT.RWF.EPORTCLK.EPCLK23PREEMPHASISWIDTH": 0    


    # For 0xA0: 19 EPCLK25-------------------------
    "LPGBT.RWF.EPORTCLK.EPCLK25LOWRES": 0             
    "LPGBT.RWF.EPORTCLK.EPCLK25INVERT": 0             
    "LPGBT.RWF.EPORTCLK.EPCLK25DRIVESTRENGTH": 3      
    "LPGBT.RWF.EPORTCLK.EPCLK25FREQ": 1              
    "LPGBT.RWF.EPORTCLK.EPCLK25PREEMPHASISSTRENGTH": 0  
    "LPGBT.RWF.EPORTCLK.EPCLK25PREEMPHASISMODE": 0     
    "LPGBT.RWF.EPORTCLK.EPCLK25PREEMPHASISWIDTH": 0    

    # EPORTTX (0xA8 - 0xC7)
    # "LPGBT.RWF.EPORTTX.EPTX3DATARATE": 0x3              
    # "LPGBT.RWF.EPORTTX.EPTX2DATARATE": 0x3              
    # "LPGBT.RWF.EPORTTX.EPTX1DATARATE": 0x3              
    # "LPGBT.RWF.EPORTTX.EPTX0DATARATE": 0x3              

    # # EPTXControl (0xA9) 
    # "LPGBT.RWF.EPORTTX.EPTX3MIRRORENABLE": 0
    # "LPGBT.RWF.EPORTTX.EPTX2MIRRORENABLE": 0
    # "LPGBT.RWF.EPORTTX.EPTX1MIRRORENABLE": 0
    # "LPGBT.RWF.EPORTTX.EPTX0MIRRORENABLE": 0

    # # EPTX10Enable (0xAA)
    # "LPGBT.RWF.EPORTTX.EPTX13ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX12ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX11ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX10ENABLE": 1                
    # "LPGBT.RWF.EPORTTX.EPTX03ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX02ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX01ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX00ENABLE": 1                

    # # EPTX32Enable (0xAB)
    # "LPGBT.RWF.EPORTTX.EPTX33ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX32ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX31ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX30ENABLE": 1                
    # "LPGBT.RWF.EPORTTX.EPTX23ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX22ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX21ENABLE": 0                
    # "LPGBT.RWF.EPORTTX.EPTX20ENABLE": 1                

    # EPTX_CHN_CONTROL (0xAE - 0xBD for EPTX00 to EPTX33, 16 channels)
    # For EPTX00 (idx 0, addr 0xAE)
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX0PREEMPHASISSTRENGTH": 0 # From 00AE:03
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX0PREEMPHASISMODE": 0   # From 00AE:03
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX0DRIVESTRENGTH": 3     # From 00AE:03

    # # For EPTX10 (idx 4, addr 0xB2)
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX4PREEMPHASISSTRENGTH": 0 # From 00B2:03
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX4PREEMPHASISMODE": 0   # From 00B2:03
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX4DRIVESTRENGTH": 3     # From 00B2:03

    # # For EPTX20 (idx 8, addr 0xB6)
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX8PREEMPHASISSTRENGTH": 0 # From 00B6:03
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX8PREEMPHASISMODE": 0   # From 00B6:03
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX8DRIVESTRENGTH": 3     # From 00B6:03

    # # For EPTX30 (idx 12, addr 0xBA)
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX12PREEMPHASISSTRENGTH": 0 # From 00BA:03
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX12PREEMPHASISMODE": 0  # From 00BA:03
    # "LPGBT.RWF.EPORTTX.EPTX_CHN_CONTROL.EPTX12DRIVESTRENGTH": 3    # From 00BA:03

    # EPORTRX (0xC8 - 0xF6)
    # EPRX0Control (0xC8)
    # "LPGBT.RWF.EPORTRX.EPRX03ENABLE": 0               
    # "LPGBT.RWF.EPORTRX.EPRX02ENABLE": 1               
    # "LPGBT.RWF.EPORTRX.EPRX01ENABLE": 0               
    # "LPGBT.RWF.EPORTRX.EPRX00ENABLE": 1               
    # "LPGBT.RWF.EPORTRX.EPRX0DATARATE": 2              
    # "LPGBT.RWF.EPORTRX.EPRX0TRACKMODE": 2             

    # # EPRX1Control (0xC9)
    # "LPGBT.RWF.EPORTRX.EPRX13ENABLE": 0               # From 00C9:5A
    # "LPGBT.RWF.EPORTRX.EPRX12ENABLE": 1               # From 00C9:5A
    # "LPGBT.RWF.EPORTRX.EPRX11ENABLE": 0               # From 00C9:5A
    # "LPGBT.RWF.EPORTRX.EPRX10ENABLE": 1               # From 00C9:5A
    # "LPGBT.RWF.EPORTRX.EPRX1DATARATE": 2              # From 00C9:5A
    # "LPGBT.RWF.EPORTRX.EPRX1TRACKMODE": 2             # From 00C9:5A

    # # EPRX2Control (0xCA)
    # "LPGBT.RWF.EPORTRX.EPRX23ENABLE": 0               # From 00CA:5A
    # "LPGBT.RWF.EPORTRX.EPRX22ENABLE": 1               # From 00CA:5A
    # "LPGBT.RWF.EPORTRX.EPRX21ENABLE": 0               # From 00CA:5A
    # "LPGBT.RWF.EPORTRX.EPRX20ENABLE": 1               # From 00CA:5A
    # "LPGBT.RWF.EPORTRX.EPRX2DATARATE": 2              # From 00CA:5A
    # "LPGBT.RWF.EPORTRX.EPRX2TRACKMODE": 2             # From 00CA:5A

    # # EPRX3Control (0xCB)
    # "LPGBT.RWF.EPORTRX.EPRX33ENABLE": 0               # From 00CB:5A
    # "LPGBT.RWF.EPORTRX.EPRX32ENABLE": 1               # From 00CB:5A
    # "LPGBT.RWF.EPORTRX.EPRX31ENABLE": 0               # From 00CB:5A
    # "LPGBT.RWF.EPORTRX.EPRX30ENABLE": 1               # From 00CB:5A
    # "LPGBT.RWF.EPORTRX.EPRX3DATARATE": 2              # From 00CB:5A
    # "LPGBT.RWF.EPORTRX.EPRX3TRACKMODE": 2             # From 00CB:5A

    # EPRX_CHN_CONTROL (0xD0 - 0xEB for EPRX0 to EPRX27)
    # For EPRX00 (idx 0, addr 0xD0)
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX0PHASESELECT": 5  # From 00D0:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX0INVERT": 0       # From 00D0:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX0ACBIAS": 1       # From 00D0:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX0TERM": 1         # From 00D0:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX0EQ1": 0          # From 00D0:56

    # # For EPRX02 (idx 2, addr 0xD2)
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX2PHASESELECT": 5  # From 00D2:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX2INVERT": 0       # From 00D2:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX2ACBIAS": 1       # From 00D2:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX2TERM": 1         # From 00D2:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX2EQ1": 0          # From 00D2:56

    # # For EPRX10 (idx 4, addr 0xD4)
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX4PHASESELECT": 5  # From 00D4:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX4INVERT": 0       # From 00D4:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX4ACBIAS": 1       # From 00D4:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX4TERM": 1         # From 00D4:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX4EQ1": 0          # From 00D4:56

    # # For EPRX12 (idx 6, addr 0xD6)
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX6PHASESELECT": 5  # From 00D6:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX6INVERT": 0       # From 00D6:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX6ACBIAS": 1       # From 00D6:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX6TERM": 1         # From 00D6:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX6EQ1": 0          # From 00D6:56

    # # For EPRX20 (idx 8, addr 0xD8)
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX8PHASESELECT": 5  # From 00D8:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX8INVERT": 0       # From 00D8:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX8ACBIAS": 1       # From 00D8:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX8TERM": 1         # From 00D8:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX8EQ1": 0          # From 00D8:56

    # # For EPRX22 (idx 10, addr 0xDA)
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX10PHASESELECT": 5 # From 00DA:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX10INVERT": 0      # From 00DA:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX10ACBIAS": 1      # From 00DA:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX10TERM": 1        # From 00DA:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX10EQ1": 0         # From 00DA:56

    # # For EPRX30 (idx 12, addr 0xDC)
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX12PHASESELECT": 5 # From 00DC:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX12INVERT": 0      # From 00DC:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX12ACBIAS": 1      # From 00DC:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX12TERM": 1        # From 00DC:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX12EQ1": 0         # From 00DC:56
    
    # # For EPRX32 (idx 14, addr 0xDE)
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX14PHASESELECT": 5 # From 00DE:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX14INVERT": 0      # From 00DE:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX14ACBIAS": 1      # From 00DE:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX14TERM": 1        # From 00DE:56
    # "LPGBT.RWF.EPORTRX.EPRX_CHN_CONTROL.EPRX14EQ1": 0         # From 00DE:56

    # # EPRXLockFilter (0xF2 ; 2D)
    "LPGBT.RWF.EPORTRX.EPRXLOCKTHRESHOLD": 0x5
    "LPGBT.RWF.EPORTRX.EPRXRELOCKTHRESHOLD": 0x5
    "LPGBT.RWF.EPORTRX.EPRXUNLOCKTHRESHOLD": 0x5

    # Datapath configuration
    "LPGBT.RW.DEBUG.DLDPBYPASDEINTERLEVEAR": 0x0
    "LPGBT.RW.DEBUG.DLDPBYPASFECDECODER": 0x0
    "LPGBT.RW.DEBUG.DLDPBYPASSDESCRAMBLER": 0x0
    "LPGBT.RW.DEBUG.DLDPFECCOUNTERENABLE": 0x1
    "LPGBT.RW.DEBUG.ULDPBYPASSINTERLEAVER": 0x0
    "LPGBT.RW.DEBUG.ULDPBYPASSSCRAMBLER": 0x0
    "LPGBT.RW.DEBUG.ULDPBYPASSFECCODER": 0x0

    # POWERUP2 (0xFB)
    "LPGBT.RWF.POWERUP.DLLCONFIGDONE": 1              # From 00FB:6
    "LPGBT.RWF.POWERUP.PLLCONFIGDONE": 1              # From 00FB:6
           

# EC Channel Configuration for LpGBT v1
ec:
  v0:
  v1:
    # EPRX EC Settings
    "LPGBT.RWF.EPORTRX.EPRXECENABLE": 1                 # From 00CF:10 -> (0x10 & 0x10) >> 4
    "LPGBT.RWF.EPORTRX.EPRXECAUTOPHASERESETDISABLE": 0  # From 00CF:10 -> (0x10 & 0x02) >> 1
    "LPGBT.RWF.EPORTRX.EPRXECTRACKMODE": 0              # From 00CF:10 -> (0x10 & 0x01)
    "LPGBT.RWF.EPORTRX.EPRXECPHASESELECT": 0  # From 00EC:2 -> (0x02 & 0x70) >> 4
    "LPGBT.RWF.EPORTRX.EPRXECINVERT": 0       # From 00EC:2 -> (0x02 & 0x08) >> 3
    "LPGBT.RWF.EPORTRX.EPRXECACBIAS": 0       # From 00EC:2 -> (0x02 & 0x04) >> 2
    "LPGBT.RWF.EPORTRX.EPRXECTERM": 1         # From 00EC:2 -> (0x02 & 0x02) >> 1
    "LPGBT.RWF.EPORTRX.EPRXECPULLUPENABLE": 0 # From 00EC:2 -> (0x02 & 0x01)

    # EPTX EC Settings
    "LPGBT.RWF.EPORTTX.EPTXECDRIVESTRENGTH": 3 # From 00AC:61 -> (0x61 & 0xE0) >> 5
    "LPGBT.RWF.EPORTTX.EPTXECINVERT": 0        # From 00AC:61 -> (0x61 & 0x04) >> 2
    "LPGBT.RWF.EPORTTX.EPTXECTRISTATE": 0      # From 00AC:61 -> (0x61 & 0x02) >> 1
    "LPGBT.RWF.EPORTTX.EPTXECENABLE": 1        # From 00AC:61 -> (0x61 & 0x01)
    # # EPTXEcChnCntr2 (0xAD)
    # "LPGBT.RWF.EPORTTX.EPTXECPREEMPHASISWIDTH": 0
    # "LPGBT.RWF.EPORTTX.EPTXECPREEMPHASISMODE": 0
    # "LPGBT.RWF.EPORTTX.EPTXECPREEMPHASISSTRENGTH": 0

    # EPCLK28 for EC (from previous v1 config as not overridden)
    # Address for EPCLK28 H-byte (0x6E + 28*2 = 0x6E + 0x38 = 0xA6)
    # Address for EPCLK28 L-byte (0xA7)
    "LPGBT.RWF.EPORTCLK.EPCLK28LOWRES": 0            
    "LPGBT.RWF.EPORTCLK.EPCLK28INVERT": 1           
    "LPGBT.RWF.EPORTCLK.EPCLK28DRIVESTRENGTH": 4     
    "LPGBT.RWF.EPORTCLK.EPCLK28FREQ": 1              
    "LPGBT.RWF.EPORTCLK.EPCLK28PREEMPHASISSTRENGTH": 0  
    "LPGBT.RWF.EPORTCLK.EPCLK28PREEMPHASISMODE": 0    
    "LPGBT.RWF.EPORTCLK.EPCLK28PREEMPHASISWIDTH": 0   